apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ccbd
    release: master
  name: ccbd-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccbd
      release: master
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ccbd
        fluent-bit: "true"
        release: master
    spec:
      containers:
      - env:
        - name: spring.profiles.active
          value: test
        - name: cytric_trip_api_url
          value: https://cytric-dummy:18080/cytric/trip
        - name: spring.security.oauth2.client.registration.keycloak.client-id
          value: ccbd
        - name: ssl.keycloak.truststore
          value: file:/opt/truststore/mom.p12
        - name: ssl.keycloak.truststore-password
          value: Amadeus06
        - name: ssl.cloud-config.truststore-password
          value: Amadeus06
        - name: ssl.cloud-config.truststore
          value: file:/opt/truststore/mom.p12
        - name: spring.cloud.config.uri
          value: https://config-server.config:8888/
        - name: spring.security.oauth2.client.provider.keycloak.token-uri
          value: https://keycloak-http.keycloak:8443/auth/realms/cytricNG/protocol/openid-connect/token
        - name: spring.security.oauth2.client.registration.keycloak.client-secret
          value: e001300a-f5d6-4bb3-bdb6-6dea987c0b6c
        - name: spring.security.oauth2.client.registration.keycloak.authorization-grant-type
          value: client_credentials
        image: nexus.secure.ifao.net:9343/ccbd-master:152
        imagePullPolicy: Always
        name: ccbd
        ports:
        - containerPort: 8080
          name: ccbd-web
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - mountPath: /opt/truststore
          name: mom
          readOnly: true
        - mountPath: /opt/keystore
          name: ccbd-keystore
          readOnly: true
      - command:
        - /go/bin/agent-linux
        - --log-level
        - debug
        env:
        - name: REPORTER_GRPC_HOST_PORT
          value: jaeger-collector:14250
        - name: JAEGER_REPORTER_LOG_SPANS
          value: "true"
        image: jaegertracing/jaeger-agent:1.18.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: admin
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: jaeger-agent-sidecar
        ports:
        - containerPort: 14271
          name: admin
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: admin
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: nexus
      restartPolicy: Always
      volumes:
      - name: mom
        secret:
          defaultMode: 420
          secretName: mom-truststore
      - name: ccbd-keystore
        secret:
          defaultMode: 420
          secretName: ccbd-keystore

